// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API.Data;

#nullable disable

namespace WEB_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API.Models.tbNhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TENNHOM");

                    b.HasKey("MaNhom");

                    b.ToTable("tbNHOM");
                });

            modelBuilder.Entity("WEB_API.Models.tbThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATHIETBI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DONVITINH");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HINHANH");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TENTHIETBI");

                    b.HasKey("MaThietBi");

                    b.ToTable("tbTHIETBI");
                });
#pragma warning restore 612, 618
        }
    }
}
