// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API.Data;

#nullable disable

namespace WEB_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251022121440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API.Models.tbDanhMuc", b =>
                {
                    b.Property<int>("IDDANHMUC")
                        .HasColumnType("int");

                    b.Property<string>("TENDANHMUC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("tbDANHMUC");

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("WEB_API.Models.tbMenu", b =>
                {
                    b.Property<decimal?>("DONGIA")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("DONVITINH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HINHANH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDDANHMUC")
                        .HasColumnType("int");

                    b.Property<int>("IDMON")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<string>("TENMON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("tbMENU");

                    b.ToView(null, (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
